name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integ-test:
    name: "Integration Test"
    environment: "IntegTest"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ format('{0}.integ-test', github.run_id) }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Inject Amplify Config File
        run: |
          aws s3 cp s3://${{ secrets.AWS_BUCKET_NAME }}/aws-appsync-apollo-extensions.json \
          ./Tests/IntegrationTestApp/IntegrationTestApp/amplify_outputs.json
      - name: "Running Integration Test"
        working-directory: "./Tests/IntegrationTestApp"
        run: |
          xcodebuild test \
          -scheme IntegrationTestApp \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
          -sdk iphonesimulator \
          | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}
